[phases.setup]
nixPkgs = ['maven', 'jdk21']

[phases.build]
cmds = ['./mvnw clean package -DskipTests']

[phases.start]
cmd = 'java -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=$PORT -jar target/quarkus-app/quarkus-run.jar'
